### ISSUE TITLE
Define __STM32U5xx_HAL_VERSION_SUB1 and __STM32U5xx_HAL_VERSION_SUB2 are not correct on version 1.7

### ISSUE THREAD

**Issue by cledic** [STMicroelectronics/stm32u5xx-hal-driver#17]
The __STM32U5xx_HAL_VERSION_SUB1 and __STM32U5xx_HAL_VERSION_SUB2 define inside stm32u5xx_hal.c file indicate a 1.6.1 version instend of 1.7

**Comment by ALABSTM** [comment]
Hi @cledic,

Thank you for having reported. Actually, version **1.7.0** is the one applicable to the [STM32CubeU5](https://github.com/STMicroelectronics/STM32CubeU5) firmware as a whole.

Each component the firmware is made of (**e.g.**, CMSIS, HAL-LL, MW) has, in turn, its own version. Particularly, the HAL-LL drivers included in the firmware are currently versioned **1.6.1**.

You can have a look at the firmware's [release note](https://htmlpreview.github.io/?https://github.com/STMicroelectronics/STM32CubeU5/blob/master/Release_Notes.html) for an overview of the versions of the different components. At the bottom of each section in the firmware history, you will find tables listing the different components and their versions.

I hope I could clarify this point. Do not hesitate otherwise.

With regards,

**Comment by cledic** [comment]
Hello Ali, thank you very much for the explanation.
I am working for the company Dodotronic. The software I am developing is
being tested on various devices for thorough trials. I would like to keep
track of the different firmware versions installed, and in addition to
managing my own version, I also want to track the version of the libraries
used. Is there a way to reference the version of the entire CubeMX software?

Thanks
Best Regards
Clemente

**Comment by ALABSTM** [comment]
Hi @cledic,

I could not find `__STM32U5_XXX_VERSION_MAIN` and macros alike related to the firmware as a whole.

However, you can find ones defined for the [CMSIS](https://github.com/STMicroelectronics/cmsis-device-u5/blob/e810729e515d3aed9b6077190d33565ff6ba06c8/Include/stm32u5xx.h#L94-L101) interface and the [HAL-LL](https://github.com/STMicroelectronics/stm32u5xx-hal-driver/blob/5f3b1924e386eb80963e1a8ec382ad08902e2a0d/Src/stm32u5xx_hal.c#L57-L64) drivers. You can also find such definitions in **each** BSP **Board** drivers, like the [STM32U575I-EV](https://github.com/STMicroelectronics/stm32u575i-ev-bsp/blob/83d8fb77a80a4c6d458f37f6ec10471ba95ddc96/stm32u575i_eval.h#L203-L210).

As for the firmware, you can refer to the [release note](https://htmlpreview.github.io/?https://github.com/STMicroelectronics/STM32CubeU5/blob/main/Release_Notes.html) of the STM32CubeU5 firmware or the list of [tags](https://github.com/STMicroelectronics/STM32CubeU5/tags).

With regards,

**Comment by cledic** [comment]
Many thanks Alì

Il lun 9 dic 2024, 09:49 Ali LABBENE ***@***.***> ha scritto:
